spring:
  datasource:
    #    url: jdbc:postgresql://localhost:5432/mydb
    url: jdbc:postgresql://tasktracker.cngmb0hrfw6b.us-east-1.rds.amazonaws.com:5432/task
    username: userName
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    #    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        format_sql: true
        temp.use_jdbc_metadata_defaults: false
  ldap:
    embedded:
      ldif: "classpath:test-server.ldif"
      base-dn: "dc=springframework,dc=org"
      port: 8389